# Generated by Django 5.1.1 on 2024-09-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalHome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptops',
            name='id',
        ),
        migrations.AlterField(
            model_name='laptops',
            name='laptop_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
