# Generated by Django 5.1.1 on 2024-09-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalHome', '0002_remove_laptops_id_alter_laptops_laptop_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='laptops',
            table='laptops',
        ),
    ]
